### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by tobisupreme** [AltCamp/altcampv1-frontend#248]
### 📜 Description

The bookmarks page bugs out when a bookmarked resource has been deleted

### 👟 Reproduction steps

- Create a resource (question)
- Add the resource to your bookmarks
- Delete the resource
- Check your bookmarks

### 👍 Expected behavior

It should render the bookmarks page. Bookmarks of resources that have been deleted should say so. A message like "this bookmarked resource is no longer available".

### 👎 Actual Behavior with Screenshots

![Bugged out bookmarks page on AltCamp](https://i.ibb.co/KKNcKmy/Screenshot-from-2023-08-01-17-25-58.png)

The page breaks

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/AltCamp/altcampv1-frontend/blob/dev/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Boye95** [comment]
Thanks @tobisupreme. Everything here has been noted and will be worked on.
