### ISSUE TITLE
No email verification on signup

### ISSUE THREAD

**Issue by tobisupreme** [AltCamp/altcampv1-frontend#260]
### 📜 Description

When a user signs up, they are taken straight to the homepage

### 👟 Reproduction steps

1. Go to https://altcampv1.netlify.app
2. Register a new account

### 👍 Expected behavior

A pop up asking the user to enter the OTP sent to their email address should be shown

### 👎 Actual Behavior with Screenshots

It actually allows the user straight to the app

![](https://i.ibb.co/gzjyMgP/no-verification-on-signup.gif)

### 📃 Provide any additional context for the Bug.

An OTP is sent to the email address provided on sign up. 
Attempting to carry out other activities that only verified users can partake in triggers the activation process.

![verification triggered on liking a post](https://i.ibb.co/1Zkqn5g/triggered-on-like.gif)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/AltCamp/altcampv1-frontend/blob/dev/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Boye95** [comment]
Thanks @tobisupreme. These issues will be looked into.

**Comment by vader-js** [comment]
Thank you @tobisupreme for bringing this to our notice
