### ISSUE TITLE
🚀 Feature: Clicking the comment icon should lead to the comments input section

### ISSUE THREAD

**Issue by vader-js** [AltCamp/altcampv1-frontend#282]
### 🔖 Feature description

currently, we have only the post box view leading to the section where comments can be added and that is not user-friendly. The comments icon should lead there as well

### 🎤 Why is this feature needed ?

The introduction of the function in the comments icon makes it a feature that is easily recognizable and user-friendly

### ✌️ How do you aim to achieve this?

This feature exists when you click the post in the feed, it leads you to the comments section. In order to make it more user friendly, it would be best to also have this feature when you click the comments icon

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/AltCamp/altcampv1-frontend/blob/dev/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Boye95** [comment]
Thanks @vader-js. I'd like to work on this.
