### ISSUE TITLE
🐛 Bug Report:  Landing Page Navigation Links are not functional

### ISSUE THREAD

**Issue by t-bello7** [AltCamp/altcampv1-frontend#283]
### 📜 Description

The nav links on the landing page are not functional 

### 👟 Reproduction steps

Go to https://altcampv1.netlify.app
Click on home or about or features link
It does not go anywhere

### 👍 Expected behavior

Clicking the nav links should scroll down to the various sections 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/AltCamp/altcampv1-frontend/assets/24270269/bc2e355a-b5c5-4386-98f6-7ce3c7eddf2b)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/AltCamp/altcampv1-frontend/blob/dev/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Boye95** [comment]
Thanks @t-bello7 for this. I can also see that you've opened a PR on this.

**Comment by t-bello7** [comment]
Yes can you kindly review

**Comment by Boye95** [comment]
I have done that.
